# Configuration for https://github.com/actions/labeler

# Label for any changes to Python files
lang-python:
  - "**/*.py"

# Label for any changes to tests
testing:
  - "tests/**/*"
  - "**/*test*.py"

# Label for any changes to CI/CD
internal:
  - ".github/**/*"
  - "**/*.yml"
  - "**/*.yaml"
  - "deploy.sh"

# Label for any changes to dependencies
upgrade:
  - "requirements*.txt"
  - "pyproject.toml"
  - "uv.lock"

# Label for infrastructure changes
infrastructure:
  - "cloudformation-template.yaml"
  - "**/infrastructure/**/*"

# Label for any changes to the main application logic
feature:
  - "lambda_function.py"
  - "src/**/*"
