name: Labels
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      # For label-checker
      - labeled
      - unlabeled

jobs:
  labeler:
    name: Auto Label PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}
        with:
          # Checkout the head ref so we get the PR changes
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/labeler@v6
        if: ${{ github.event.action != 'labeled' && github.event.action != 'unlabeled' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
      - run: echo "Done adding labels"
  # Run this after labeler applied labels
  check-labels:
    needs:
      - labeler
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: breaking,security,feature,bug,refactor,upgrade,docs,lang-python,testing,internal,infrastructure
          repo_token: ${{ secrets.GITHUB_TOKEN }}
